source 'https://rubygems.org'
gem 'fluentd', '>=0.12.32'
gem 'activesupport', '<5'
gem 'public_suffix', '<3.0.0'
gem 'fluent-plugin-rewrite-tag-filter', '<2.0.0'
gem 'fluent-plugin-record-modifier', '<1.0.0'
gem 'fluent-plugin-kubernetes_metadata_filter'
gem 'fluent-plugin-secure-forward'
gem 'fluent-plugin-remote_syslog', '<1.0.0'
gem 'fluent-plugin-splunk-ex'
gem 'fluent-plugin-splunk-hec'

